# ---------------- Application ----------------
spring.application.name=p1
server.port=${PORT:8080}

# ---------------- Database (H2 - temporary) ----------------
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ---------------- Email Configuration ----------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=harsh6387842@gmail.com
spring.mail.password=umbobgfqlxdtjibm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ---------------- Logging ----------------
logging.level.org.springframework.mail=DEBUG

# ---------------- API Key ----------------
gemini.api.key=${GOOGLE_API_KEY}
